<a href="https://colab.research.google.com/github/nursultahn/InterviewTasks/blob/main/train_target_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
# train = pd.read_csv('/content/drive/MyDrive/FreedomTest/train.csv')
# test = pd.read_csv('/content/drive/MyDrive/FreedomTest/test.csv')

In [4]:
# Скопируем оригинальный DataFrame
# train_data_target1 = train.copy()
train_data_target1 = pd.read_csv('/content/drive/MyDrive/FreedomTest/train.csv')
# Удалим столбец target_2
train_data_target1 = train_data_target1.drop(columns='target_2')

In [5]:
train_data_target1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 647734 entries, 0 to 647733
Columns: 182 entries, Unnamed: 0 to SCORE_11_15
dtypes: float64(173), int64(8), object(1)
memory usage: 899.4+ MB

In [6]:
categorical_columns = train_data_target1.select_dtypes(include=['object']).columns
print(categorical_columns)

Index([' с_date'], dtype='object')

In [7]:
train_data_target1['с_date'] = pd.to_datetime(train_data_target1[' с_date'])
train_data_target1['с_date_datetime'] = pd.to_datetime(train_data_target1[' с_date'])
train_data_target1['с_date_year'] = train_data_target1['с_date_datetime'].dt.year
train_data_target1['с_date_month'] = train_data_target1['с_date_datetime'].dt.month
train_data_target1['с_date_day'] = train_data_target1['с_date_datetime'].dt.day
train_data_target1['с_date_dayofweek'] = train_data_target1['с_date_datetime'].dt.dayofweek
train_data_target1.drop([' с_date'], axis=1, inplace=True)
train_data_target1.drop(['с_date_datetime'], axis=1, inplace=True)
train_data_target1.drop(['Unnamed: 0'], axis=1, inplace=True)
train_data_target1.drop(['ID_NEW'], axis=1, inplace=True)
train_data_target1.drop(['с_date'], axis=1, inplace=True)

In [8]:
train_data_target1.head()

,Score_p,Score_bm,Score_ae,Score_vy,Score_vt,Score_r,Score_bcb,Score_ow,Score_ow_sh,target_1,...,SCORE_7_6,SCORE_7_7,SCORE_7_8,SCORE_7_9,SCORE_9_25,SCORE_11_15,с_date_year,с_date_month,с_date_day,с_date_dayofweek
0,16651,6.0,2,1993,4,7,1,1.110100e+08,1110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,13,1
1,16551,2.0,2,2017,4,10,0,1.556391e+09,1556.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,8,3
2,16651,5.0,1,1993,4,7,1,1.110100e+08,1110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,13,1
3,2920,13.0,4,2014,4,19,1,5.110111e+08,5110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,9,4
4,1027,13.0,4,2014,10,12,0,4.352301e+09,4352.0,0.0,...,NaN,NaN,NaN,NaN,2.0,0.0,2020,7,30,3

In [9]:
pd.set_option('display.max_rows', None)

In [10]:
# Вычисляем процент пропущенных значений для каждого признака
missing_percent = train_data_target1.isnull().sum() * 100 / len(train_data_target1)

# Определяем признаки, где процент пропущенных значений больше 50
features_to_drop = missing_percent[missing_percent > 50].index

# Удаляем эти признаки из датафрейма
train_data_target1 = train_data_target1.drop(features_to_drop, axis=1)

In [11]:
train_data_target1.head()

,Score_p,Score_bm,Score_ae,Score_vy,Score_vt,Score_r,Score_bcb,Score_ow,Score_ow_sh,target_1,...,SCORE_6_6,SCORE_6_7,SCORE_6_8,SCORE_6_9,SCORE_9_25,SCORE_11_15,с_date_year,с_date_month,с_date_day,с_date_dayofweek
0,16651,6.0,2,1993,4,7,1,1.110100e+08,1110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,13,1
1,16551,2.0,2,2017,4,10,0,1.556391e+09,1556.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,8,3
2,16651,5.0,1,1993,4,7,1,1.110100e+08,1110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,13,1
3,2920,13.0,4,2014,4,19,1,5.110111e+08,5110.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,4,9,4
4,1027,13.0,4,2014,10,12,0,4.352301e+09,4352.0,0.0,...,9.0,10.0,10.0,9.0,2.0,0.0,2020,7,30,3

In [12]:
import numpy as np

# Заполнение пропущенных значений медианой для числовых признаков
for col in train_data_target1.select_dtypes(include=np.number).columns:
    train_data_target1[col].fillna(train_data_target1[col].median(), inplace=True)

In [13]:
X = train_data_target1.drop('target_1', axis=1)
y = train_data_target1['target_1']

In [14]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, mean_squared_error

# Создаем бинарную целевую переменную
y_binary = (y != 0).astype(int)

# Разделяем данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test, y_binary_train, y_binary_test = train_test_split(X, y, y_binary, test_size=0.2, random_state=42)

# Применяем oversampling только для меньшего класса
ros = RandomOverSampler(sampling_strategy='minority')
X_res, y_binary_res = ros.fit_resample(X_train, y_binary_train)

# Обучаем модель классификации
classifier = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
classifier.fit(X_res, y_binary_res)

# Делаем предсказания классификации
y_binary_pred = classifier.predict(X_test)

# Выводим метрики классификации
print('Accuracy:', accuracy_score(y_binary_test, y_binary_pred))
print('F1 score:', f1_score(y_binary_test, y_binary_pred))
print('ROC AUC score:', roc_auc_score(y_binary_test, y_binary_pred))

# Обучаем модель регрессии только на ненулевых значениях
X_regression_train = X_train[y_train != 0]
y_regression_train = y_train[y_train != 0]

regressor = XGBRegressor(random_state=42)
regressor.fit(X_regression_train, y_regression_train)

# Делаем предсказания регрессии только для ненулевых предсказаний классификации
X_regression_test = X_test[y_binary_pred != 0]
y_regression_test = y_test[y_binary_pred != 0]

if len(X_regression_test) > 0:
    y_regression_pred = regressor.predict(X_regression_test)

    # Выводим метрику регрессии
    print('RMSE:', np.sqrt(mean_squared_error(y_regression_test, y_regression_pred)))
else:
    print('No non-zero predictions were made.')

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")

Accuracy: 0.8686422688290736
F1 score: 0.036246247946989864
ROC AUC score: 0.6062867990996994
RMSE: 1090757.4349885923

In [15]:
test = pd.read_csv('/content/drive/MyDrive/FreedomTest/test.csv')

In [16]:
test_data_target1 = test.copy()

In [17]:
ID_NEW_test = test_data_target1['ID_NEW']

In [18]:
test_data_target1['с_date'] = pd.to_datetime(test_data_target1[' с_date'])
test_data_target1['с_date_datetime'] = pd.to_datetime(test_data_target1[' с_date'])
test_data_target1['с_date_year'] = test_data_target1['с_date_datetime'].dt.year
test_data_target1['с_date_month'] = test_data_target1['с_date_datetime'].dt.month
test_data_target1['с_date_day'] = test_data_target1['с_date_datetime'].dt.day
test_data_target1['с_date_dayofweek'] = test_data_target1['с_date_datetime'].dt.dayofweek
test_data_target1.drop([' с_date'], axis=1, inplace=True)
test_data_target1.drop(['с_date_datetime'], axis=1, inplace=True)
test_data_target1.drop(['Unnamed: 0'], axis=1, inplace=True)
test_data_target1.drop(['ID_NEW'], axis=1, inplace=True)
test_data_target1.drop(['с_date'], axis=1, inplace=True)

In [19]:
new_test_data_target1 = test_data_target1.filter(X_res.columns)

In [20]:
# Заполнение пропущенных значений медианой для числовых признаков
for col in new_test_data_target1.select_dtypes(include=np.number).columns:
    new_test_data_target1[col].fillna(new_test_data_target1[col].median(), inplace=True)

In [21]:
# Делаем предсказания классификации на новых данных
y_binary_pred_new = classifier.predict(new_test_data_target1)

# Получаем ID для ненулевых предсказаний
ID_NEW_non_zero = ID_NEW_test[y_binary_pred_new != 0]

# Делаем предсказания регрессии только для ненулевых предсказаний классификации
X_regression_new = new_test_data_target1[y_binary_pred_new != 0]

if len(X_regression_new) > 0:
    y_regression_pred_new = regressor.predict(X_regression_new)

    # Связываем предсказания с идентификаторами
    results = pd.DataFrame({'ID_NEW': ID_NEW_non_zero, 'prediction': y_regression_pred_new})
else:
    print('No non-zero predictions were made.')

# Сохраняем результаты в CSV-файл
results.to_csv('predictions.csv', index=False)

In [23]:
import pickle

# Сохранение модели классификации
with open('xgbclassifier.pkl', 'wb') as f:
    pickle.dump(classifier, f)

# Сохранение модели регрессии
with open('xgbregressor.pkl', 'wb') as f:
    pickle.dump(regressor, f)